version: '3.9'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tree-plantation
    volumes:
      - mongodb_data:/data/db
    restart: always

  client:
    build:
      context: ./Client
    container_name: client-app
    ports:
      - "3005:80"
    restart: always

  admin:
    build:
      context: ./admin
    container_name: admin-app
    ports:
      - "3001:80"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend-api
    ports:
      - "5001:3000"
    depends_on:
      - mongodb
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: Admin@12345
    restart: always

volumes:
  mongodb_data:
  grafana_data:
