apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tree-planting-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Thaanees-RM/tree-project.git
    targetRevision: production
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: tree-planting
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
